### ISSUE TITLE
Convert azzert.that(X, is(true)) to assert x

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team4#119]
_From @yossigil on November 14, 2018 20:39_

Similalry, convert azzert.that(X, is(false)) to assert !x
Similalry, convert azzert.thattrue, is(Boolean.FALSE)) to assert !x,
etc.

_Copied from original issue: TechnionYP5779/team6#90_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#133

**Comment by moshesab** [comment]
@yossigil  What about using azzert.aye(x) instead? 
You asked us to change every use of assert to azzert, and checking that a boolean expression x is true is done by azzert.aye(x) and to check that is false: azzert.nay(x)...

**Comment by yossigil** [comment]
assert x, is shorter than azzer.taye

**Comment by moshesab** [comment]
@yossigil  so should we change every azzert.aye(x) to assert x etc?

**Comment by menhel** [comment]
See image below, it is impossible to close both of these issues at the same time.
@dormaayan, Please define clear rules regarding the use of azzert vs. assert.


![image](https://user-images.githubusercontent.com/28152692/48661971-28beac00-ea83-11e8-9e3b-2ad827dbdd3d.png)

#106

**Comment by ameeramer** [comment]
@menhel I don't think there's a contradiction between the issues, this issue instructs us to use the **command** assert where possible, where the other one instructs us to use the class azzert instead of the **class** Assert. 
The class Assert and the command assert aren't the same, the first is a class of JUnit, while the second is a command in Java.

**Comment by menhel** [comment]
@ameeramer Thanks, all clear now :-)
