### ISSUE TITLE
Create a backlog for Testock website

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/team4#171]

**Comment by 0xYuval** [comment]
Created a [backlog](https://github.com/TechnionYP5779/team4/projects/1), and added 20 user stories.

The user stories are based on the following structure:
As a < type of user >, I want < some goal > so that < some reason >.

This structure is recommended by this tutorial: https://www.mountaingoatsoftware.com/agile/user-stories

At our group meeting in Wednesday, we will decide which features will get into Sprint-One, which to the next sprint, and which are considered "Nice-To-Have".

**Comment by 0xYuval** [comment]
#175
