### ISSUE TITLE
Design website template for testock

### ISSUE THREAD

**Issue by menhel** [TechnionYP5779/team4#173]
Stick to Material design principle and conform to Bootstrap layouts as much as possible
[Material Design](https://material.io/design/introduction/)
[Bootstrap Website](https://getbootstrap.com/)

**Comment by 0xYuval** [comment]
Login:
![image](https://user-images.githubusercontent.com/19504086/49824852-af695f00-fd8b-11e8-8c37-3564044534e7.png)

**Comment by 0xYuval** [comment]
Choose Faculty:
![image](https://user-images.githubusercontent.com/19504086/49824975-f9524500-fd8b-11e8-8952-c7540915ea0a.png)

**Comment by 0xYuval** [comment]
Choose Course:
![image](https://user-images.githubusercontent.com/19504086/49825151-6665da80-fd8c-11e8-8779-461e9751726e.png)

**Comment by yuvalron** [comment]
Created a backlog, and added 20 user stories.

The user stories are based on the following structure:
As a < type of user >, I want < some goal > so that < some reason >.

This structure is recommended by this tutorial: https://www.mountaingoatsoftware.com/agile/user-stories

At our group meeting in Wednesday, we will decide which features will get into Sprint-One, which to the next sprint, and which are considered "Nice-To-Have".
